_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "output/ViTAEv2_S/TotalText/pretrain/vitaev2-s_pretrain_synth-tt-mlt-13-15-textocr.pth"
  ViTAEv2:
    DROP_PATH_RATE: 0.2

DATASETS:
  TRAIN: ("maps_train",)
  TEST: ("maps_val",)

SOLVER:
  IMS_PER_BATCH: 1 #8
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (100000,)  # no step
  MAX_ITER: 5000 #440
  CHECKPOINT_PERIOD: 2000

#TEST:
#  EVAL_PERIOD: 1000


OUTPUT_DIR: "output/ViTAEv2_S/map/finetune/totaltext"