_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "output/R50/150k_tt/pretrain/res50_pretrain_synth-tt.pth"

DATASETS:
  TRAIN:  ("maps_train",) 
  TEST:  ("maps_val",) 

  #TRAIN: ("totaltext_train",)
  #TEST:  ("totaltext_test",) 
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (100000,)  # no step
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 1600

#TEST:
#  EVAL_PERIOD: 100

OUTPUT_DIR: "output/R50/map/finetune/totaltext"